# Generated by Django 3.2 on 2021-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Choice',
            field=models.CharField(choices=[('1', 'Doctor'), ('2', 'patient')], default='Doctor', max_length=25),
        ),
    ]
